version: 2.1

gcr_auth: &gcr_auth
  auth:
    username: _json_key
    password: $GCLOUD_SERVICE_ACCOUNT

jobs:
  test:
    docker:
      - image: gcr.io/outreach-docker/bootstrap/ci-slim:stable
        <<: *gcr_auth
    steps:
      - checkout
      - run:
          name: Test
          command: make test
    
workflows:
  build_and_test:
    jobs:
      - test:
          context:
            - docker-registry
