version: 2.1

orbs:
  shared: getoutreach/shared@dev:2.31.0-rc.1
  aws-s3: circleci/aws-s3@4.1.0
  aws-cli: circleci/aws-cli@5.1.1
jobs:
  test:
    executor: shared/testbed-docker-aws
    steps:
      - checkout
      - run:
          name: Test
          command: make test
  deploy:
    executor: shared/testbed-docker-aws
    steps:
      - checkout
      - run:
          name: Set AWS region
          command: echo 'export AWS_REGION=us-west-2' >> $BASH_ENV
      - run:
          name: Check branch
          command: |
            if [[ "$CIRCLE_BRANCH" != "master" && "$CIRCLE_BRANCH" != rezoan/* ]]; then
              echo "Not a deploy branch, skipping."
              circleci step halt
            fi
      - aws-cli/install
      - aws-s3/sync:
          from: .
          to: s3://jsonnet-libs.outreach.io
workflows:
  build_and_test:
    jobs:
      - test:
          context:
            - aws-credentials
            - docker-registry
  deploy:
    jobs:
      - deploy:
          context:
            - aws-credentials
            - aws-region-us-west-2
