version: 2.1
orbs:
  shared: getoutreach/shared@dev:first

jobs:
  test:
    executor: shared/testbed-docker-aws
    steps:
      - checkout
      - run:
          name: Test
          command: make test

workflows:
  build_and_test:
    jobs:
      - test:
          context:
            - aws-credentials
            - docker-registry
