version: 2.1
orbs:
  shared: getoutreach/shared@dev:2.31.0-rc.1
  aws-s3: circleci/aws-s3@4.1.0
jobs:
  test:
    executor: shared/testbed-docker-aws
    steps:
      - checkout
      - run:
          name: Test
          command: make test
  deploy:
    executor: shared/testbed-docker-aws
    steps:
      - checkout
      - run:
          name: Check branch
          command: |
            if [[ "$CIRCLE_BRANCH" != "master" && "$CIRCLE_BRANCH" != rezoan/* ]]; then
              echo "Not a deploy branch, skipping."
              circleci step halt
            fi
      - aws-s3/sync:
          from: .
          to: $AWS_DEPLOY_TARGET
workflows:
  build_and_test:
    jobs:
      - test:
          context:
            - aws-credentials
            - docker-registry
  deploy:
    jobs:
      - deploy:
          context:
            - aws-credentials
            - docker-registry
